import { motion } from "framer-motion";
import Head from "next/head";
import React from "react";
import {
  BsFillTelephoneFill,
  BsGithub,
  BsInstagram,
  BsWhatsapp,
} from "react-icons/bs";
import { HiMail } from "react-icons/hi";
import { FaLinkedinIn, FaMapMarkerAlt } from "react-icons/fa";
import {
  children,
  container,
  popIn,
  slideDown,
  slideLeftTransition,
} from "../animation/framerMotion";
import Button from "../components/Button";
import Heading from "../components/Heading";
import Link from "next/link";

export default function contact() {
  return (
    <div>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative min-h-screen flex items-center overflow-hidden px-5 md:px-10 pb-2">
        <div className="customContainer">
          <div className="flex items-center mt-20">
            <Heading text={"Contact"} search />
          </div>
          <div className="relative box h-max p-5 lg:p-10 text-[calc(1.25rem+1.5vw)] leading-[150%] col-span-9 md:col-span-5 overflow-hidden">
            <p>Get in touch</p>
            <motion.div
              variants={slideDown}
              initial="hidden"
              animate="visible"
              exit="exit"
              className="absolute top-0 h-full w-full bgDark"
            />
          </div>
          <div className="grid grid-cols-4 lg:grid-cols-5 gap-5">
            <div className="col-span-4 md:col-span-2 lg:col-span-3 mb-10 md:mb-0">
              <div className="grid grid-cols-2 gap-5 text-xl">
                <input
                  className="box py-2 px-5 col-span-2 sm:col-span-1 md:col-span-2 lg:col-span-1"
                  type="text"
                  placeholder="Name"
                />
                <input
                  className="box py-2 px-5 col-span-2 sm:col-span-1 md:col-span-2 lg:col-span-1"
                  type="text"
                  placeholder="Email"
                />
                <input
                  className="box py-2 px-5 col-span-2"
                  type="text"
                  placeholder="Subject"
                />
                <textarea
                  className="box py-2 px-5 col-span-2 h-40"
                  placeholder="Message"
                ></textarea>
                <div className="text-xl col-span-2 ml-auto">
                  <Button text={"Send"} icon={"arrow"} />
                </div>
              </div>
            </div>
            <div className="col-span-4 md:col-span-2 tracking-wide">
              <motion.div
                variants={container}
                initial="hidden"
                animate="visible"
                exit="exit"
                className="box h-full min-h-[300px] p-5 flex flex-col gap-5"
              >
                <motion.div
                  variants={children}
                  className="flex gap-5 items-center"
                >
                  <BsFillTelephoneFill />
                  <span>+8801730609558</span>
                </motion.div>
                <motion.div
                  variants={children}
                  className="flex gap-5 items-center"
                >
                  <HiMail />
                  <span className="break-all">mithilhassan007@gmail.com</span>
                </motion.div>
                <motion.div
                  variants={children}
                  className="flex gap-5 items-center"
                >
                  <FaMapMarkerAlt />
                  <span>Dhaka, Bangladesh.</span>
                </motion.div>
                <motion.div
                  variants={children}
                  className="flex justify-around mt-auto text-4xl"
                >
                  <Link href="https://github.com/MithilHassan">
                    <BsGithub className="hover:scale-125 transition-transform ease-linear" />
                  </Link>
                  <Link href="https://wa.me/01730609558">
                    <BsWhatsapp className="hover:scale-125 transition-transform ease-linear" />
                  </Link>
                  <Link href="https://www.instagram.com/mithil.hassan/">
                    <BsInstagram className="hover:scale-125 transition-transform ease-linear" />
                  </Link>
                  <Link href="https://www.linkedin.com/in/mithil-hassan/">
                    <FaLinkedinIn className="hover:scale-125 transition-transform ease-linear" />
                  </Link>
                </motion.div>
              </motion.div>
            </div>
          </div>
        </div>
        <motion.div
          variants={slideLeftTransition}
          initial="hidden"
          animate="visible"
          exit="exit"
          className="absolute top-0 h-full w-full bg-black"
        />
      </div>
    </div>
  );
}
