import { motion } from "framer-motion";
import Head from "next/head";
import { slideRightTransition } from "../animation/framerMotion";
import Hero from "../components/Hero";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mithil Hassan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative overflow-hidden">
        <Hero />
        <motion.div
          variants={slideRightTransition}
          initial="hidden"
          animate="visible"
          exit="exit"
          transition={{ delay: 1 }}
          className="absolute top-0 h-full w-full bg-black"
        />
      </main>
    </div>
  );
}
