import React from "react";
import Heading from "../components/Heading";
import Project from "../components/Project";
import { motion } from "framer-motion";
import { slideLeftTransition } from "../animation/framerMotion";
import Head from "next/head";
import { client } from "../sanity";

export default function projects({ projects }) {
  return (
    <div>
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative min-h-screen flex items-center justify-center px-5 sm:px-10 overflow-hidden">
        <div className="customContainer">
          <div className="flex items-center mt-20">
            <Heading text={"My Projects"} search />
          </div>
          <Project projects={projects} />
        </div>
        <motion.div
          variants={slideLeftTransition}
          initial="hidden"
          animate="visible"
          exit="exit"
          className="absolute top-0 h-full w-full bg-black"
        />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const projects = await client.fetch(
    `*[_type == "project"] {..., "technologies": technologies[]->} | order(order asc)`
  );
  return {
    props: {
      projects,
    },
  };
}
